# Generated by Django 4.1.8 on 2023-04-17 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quickstart", "0002_geeksmodel_delete_hero"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeeksModel",
        ),
    ]
