# Generated by Django 4.1.8 on 2023-04-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=30)),
                ("gender", models.CharField(default="Male", max_length=30)),
                ("short_name", models.CharField(default="Null", max_length=100)),
                ("model_description", models.TextField(default="No description")),
            ],
            options={
                "verbose_name": "Audio Model",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(default="¥", max_length=10)),
                ("currency_description", models.TextField(default="日本")),
            ],
        ),
        migrations.CreateModel(
            name="GPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=30)),
                ("model_description", models.TextField(default="No description")),
            ],
            options={
                "verbose_name": "GPT Model",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=30)),
                ("plan_price", models.FloatField()),
                ("request_no_per_day", models.IntegerField()),
                ("plan_description", models.TextField(default="No description")),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="plan.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanSettingGpt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.gpt"
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanSettingAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.audio"
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.plan"
                    ),
                ),
            ],
        ),
    ]
