# Generated by Django 4.1.8 on 2023-04-19 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=30)),
                ("model_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="GPT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=30)),
                ("model_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=30)),
                ("plan_price", models.FloatField()),
                ("request_no_per_day", models.IntegerField()),
                (
                    "audio_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.audio"
                    ),
                ),
                (
                    "gpt_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.gpt"
                    ),
                ),
            ],
        ),
    ]
