# Generated by Django 4.1.8 on 2023-04-19 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="audio_model",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="gpt_model",
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_description",
            field=models.TextField(default="No description"),
        ),
        migrations.CreateModel(
            name="Plan_setting_gpt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.gpt"
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan_setting_audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.audio"
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.plan"
                    ),
                ),
            ],
        ),
    ]
