# Generated by Django 4.1.8 on 2023-04-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_qacategory_qa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qa",
            options={"verbose_name": "Questions and Answer"},
        ),
        migrations.AlterModelOptions(
            name="qacategory",
            options={"verbose_name": "Question Categorie"},
        ),
        migrations.AlterField(
            model_name="qa",
            name="category_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan.qacategory",
            ),
        ),
    ]
