# Generated by Django 4.1.8 on 2023-04-19 03:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_remove_plan_audio_model_remove_plan_gpt_model_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Plan_setting_audio",
            new_name="PlanSettingAudio",
        ),
        migrations.RenameModel(
            old_name="Plan_setting_gpt",
            new_name="PlanSettingGpt",
        ),
    ]
