# Generated by Django 4.1.8 on 2023-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0003_alter_qa_options_alter_qacategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qacategory",
            name="first_category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
