# Generated by Django 4.1.8 on 2023-04-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0003_rename_plan_setting_audio_plansettingaudio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="unit",
            field=models.CharField(default="¥", max_length=10),
        ),
    ]
