# Generated by Django 4.1.8 on 2023-04-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0004_alter_qacategory_first_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qa",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plan.qacategory"
            ),
        ),
    ]
