# Generated by Django 4.1.8 on 2023-04-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0004_plan_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(default="¥", max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="plan",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plan.payunit"
            ),
        ),
    ]
