# Generated by Django 4.1.8 on 2023-04-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0005_payunit_alter_plan_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audio",
            options={"verbose_name": "Audio Model"},
        ),
        migrations.AlterModelOptions(
            name="gpt",
            options={"verbose_name": "GPT Model"},
        ),
        migrations.AddField(
            model_name="payunit",
            name="unit_description",
            field=models.TextField(default="日本"),
        ),
    ]
