# Generated by Django 4.1.8 on 2023-04-29 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0005_alter_qa_category_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qacategory",
            options={"verbose_name": "Question Category"},
        ),
    ]
