# Generated by Django 4.1.8 on 2023-04-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0006_alter_audio_options_alter_gpt_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="gender",
            field=models.CharField(default="Male", max_length=30),
        ),
        migrations.AddField(
            model_name="audio",
            name="short_name",
            field=models.CharField(default="Null", max_length=100),
        ),
    ]
