# Generated by Django 4.1.8 on 2023-04-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0007_audio_gender_audio_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="model_description",
            field=models.TextField(default="No description"),
        ),
    ]
