# Generated by Django 4.1.8 on 2023-04-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0008_alter_audio_model_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpt",
            name="model_description",
            field=models.TextField(default="No description"),
        ),
    ]
