# Generated by Django 4.1.8 on 2023-04-28 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=30)),
                ("family_name", models.CharField(max_length=100)),
                ("given_name", models.CharField(max_length=100)),
                ("mail", models.CharField(max_length=100)),
                ("mail_verified", models.BooleanField(default=False)),
                ("phone", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=300)),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="plan.plan"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Account",
            },
        ),
    ]
