# Generated by Django 4.1.8 on 2023-04-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("plan_id", models.IntegerField(max_length=2)),
                ("gender", models.CharField(max_length=30)),
                ("family_name", models.CharField(max_length=100)),
                ("given_name", models.CharField(max_length=100)),
                ("mail", models.CharField(max_length=100)),
                ("mail_verified", models.BooleanField(default=False)),
                ("phone", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=300)),
            ],
        ),
    ]
