# Generated by Django 4.1.8 on 2023-04-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0010_rename_payunit_currency"),
        ("acc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "User Account"},
        ),
        migrations.AlterField(
            model_name="account",
            name="plan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plan.plan"
            ),
        ),
    ]
